### ISSUE TITLE
doc: translate docs/end-user/components/cloud-services/provision-instance-and-database-separately

### ISSUE THREAD

**Issue by yangxggo** [oam-dev/kubevela.io#1014]
https://kubevela.net/zh/docs/end-user/components/cloud-services/provision-instance-and-database-separately

**Comment by yangxggo** [comment]
The PR #1015  has passed basic checks. Review required.

**Comment by wonderflow** [comment]
@yangxggo Hi, would you like to contact me in the dingtalk? My ID is wonderflow , I want to send you some gifts to thank you for the translation work!
