### ISSUE TITLE
Doc link is missing

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/kubevela.io#345]
https://kubevela.io/zh/docs/next/quick-start#%E6%9D%A5%E8%87%AA-git-%E4%BB%93%E5%BA%93%E7%9A%84%E7%BB%84%E4%BB%B6%EF%BC%88%E5%9F%BA%E4%BA%8E-kustomize%EF%BC%89

![image](https://user-images.githubusercontent.com/2805315/137432153-44adefa8-37c0-4b8a-80a7-7c3063b32eff.png)

**Comment by BinaryHB0916** [comment]
thx and fixed.
