### ISSUE TITLE
Installation link is broken on kubevela.io/docs

### ISSUE THREAD

**Issue by Kinrany** [oam-dev/kubevela.io#488]
Section What's Next of Introduction has a link to Installation: https://kubevela.io/docs#whats-next

The link points to https://kubevela.io/install which does not exists.

The link works for the same page with an extra `/` at the end: https://kubevela.io/docs/#whats-next

Perhaps a redirect is needed.

**Comment by wonderflow** [comment]
thanks, it's fixed now.
