### ISSUE TITLE
Provide an image for offline deploying in closed k8s cluster

### ISSUE THREAD

**Issue by xueliangyang-oeuler** [oam-dev/kubevela.io#558]
Can kubevela.io website alone deployed in offline K8s cluster.
I find an image in dockerhub, but can not run normally.
！！！HELP

here what i DO:
1) docker pull yangsoon/kubevela.io:v1
2) docker run

**Comment by xueliangyang-oeuler** [comment]
It is necessary to provide the related image of kubevela.io website to dockerhub for user in offline environment.

**Comment by fourierr** [comment]
> 
nice

**Comment by wonderflow** [comment]
Here's a demo about deploying kubevela.io by using velaux. 

- the video https://www.bilibili.com/video/BV1A34y1k756?spm_id_from=333.999.0.0
- this demo repo https://gitlab.com/Somefive/kubevela.io

**Comment by xueliangyang-oeuler** [comment]
@wonderflow  thanks !
