### ISSUE TITLE
Make offline installation more easier

### ISSUE THREAD

**Issue by xueliangyang-oeuler** [oam-dev/kubevela.io#564]
#  Declare EXPOSE in Dockerfile
# Give a standard and easy deployment method（including deployment, svc, ingress） in source code

(I build the source for the image, but now i have no idea the container port)

**Comment by fourierr** [comment]
The default port is 3000

**Comment by fourierr** [comment]
kubevela.io was based on docusaurus and the default port is 3000.

**Comment by wonderflow** [comment]
It's an addon now https://github.com/kubevela/catalog/tree/master/addons/kubevela-io
