### ISSUE TITLE
Make kubevela.io AS an addon in vela-core

### ISSUE THREAD

**Issue by xueliangyang-oeuler** [oam-dev/kubevela.io#569]

**Comment by wonderflow** [comment]
good idea, would you like to contribute it?

**Comment by xueliangyang-oeuler** [comment]
@wonderflow  The PR for the feature: https://github.com/oam-dev/catalog/pull/321#issue-1206073504

**Comment by wonderflow** [comment]
great!

**Comment by xueliangyang-oeuler** [comment]
close with https://github.com/kubevela/catalog/pull/321#issue-1206073504
