### ISSUE TITLE
add favicons

### ISSUE THREAD

**Issue by Arhell** [oam-dev/kubevela.io#673]
https://realfavicongenerator.net/favicon_checker?protocol=https&site=kubevela.io%2F#.Yo32sKjP23A
/assign

**Comment by wonderflow** [comment]
@Arhell great, do you need any resources?

**Comment by Arhell** [comment]
> @Arhell great, do you need any resources?

Thanks, no.

**Comment by wonderflow** [comment]
![image](https://user-images.githubusercontent.com/2173670/170725403-5949e1fb-dd4d-4d36-b073-fc028bae37ee.png)


@Arhell  Hi, I think there's some issue about the resource.

**Comment by wonderflow** [comment]
It should be transparent.
