### ISSUE TITLE
remove package-lock.json

### ISSUE THREAD

**Issue by Arhell** [oam-dev/kubevela.io#748]
unnecessary file

**Comment by wonderflow** [comment]
it's maybe useful? Some frontend projects prefer to keep it.

**Comment by Arhell** [comment]
> it's maybe useful? Some frontend projects prefer to keep it.

The project already has yarn.lock, I think this will be enough.

**Comment by wonderflow** [comment]
sure, then we must clean the script in github actions, it both use yarn and npm. https://github.com/kubevela/kubevela.io/blob/main/.github/workflows/documentation.yml
