### ISSUE TITLE
translate addon docs to i18n/zh

### ISSUE THREAD

**Issue by wangyikewxgm** [oam-dev/kubevela.io#761]
https://kubevela.net/zh/docs/reference/addons/overview
https://kubevela.net/zh/docs/reference/addons/velaux
https://kubevela.net/zh/docs/reference/addons/cert-manager
https://kubevela.net/zh/docs/reference/addons/kubevela-io
https://kubevela.net/zh/docs/reference/addons/pyroscope
https://kubevela.net/zh/docs/reference/addons/vegeta
https://kubevela.net/zh/docs/reference/addons/ocm-gateway-manager-addon
https://kubevela.net/zh/docs/reference/addons/ocm-hub-control-plane
https://kubevela.net/zh/docs/reference/addons/vela-prism
https://kubevela.net/zh/docs/reference/addons/flink-kubernetes-operator

**Comment by qunqiang** [comment]
I want to translate this issue.

**Comment by qunqiang** [comment]
All translated pages have been merged, so this issue can be closed.

**Comment by wonderflow** [comment]
Thanks @qunqiang
