### ISSUE TITLE
Add subscription for our blog

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela.io#801]
The subscription can help send notification email when new blog released.

**Comment by wonderflow** [comment]
ping @Arhell  

Would that impossible for our current blog framework?

**Comment by Arhell** [comment]
alas, I did not find such a plugin

**Comment by nikhilchauhangithub** [comment]
@wonderflow Kindly assign me this issue, I would love to work on it

**Comment by wonderflow** [comment]
@nikhilchauhangithub Thanks for your work!

**Comment by nikhilchauhangithub** [comment]
@wonderflow My pleasure, to work with you and @chivalryq
