### ISSUE TITLE
translate canary rollout for container service

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela.io#803]
https://kubevela.io/zh/docs/end-user/traits/rollout

**Comment by oudi** [comment]
I would try to translate this doc. assign to me:)

**Comment by oudi** [comment]
@wonderflow need for your preview https://github.com/kubevela/kubevela.io/pull/848

**Comment by oudi** [comment]
committed and merged, can close now.

**Comment by wonderflow** [comment]
thanks for your contribution！ @oudi
