### ISSUE TITLE
translate canary rollout for helm

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela.io#804]
https://kubevela.io/zh/docs/tutorials/helm-rollout

**Comment by oudi** [comment]
I would try to translate this doc. assign to me:)

**Comment by oudi** [comment]
@wonderflow after a couple of failed attempts, https://github.com/kubevela/kubevela.io/pull/852 shows every action goes well. waiting for your review.

**Comment by oudi** [comment]
committed and merged, can close now.
