### ISSUE TITLE
translate of vela cli image docs

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela.io#807]
https://kubevela.io/zh/docs/next/platform-engineers/system-operation/vela-cli-image

**Comment by dazuimao1990** [comment]
I am very interested in this work and will submit PR in the near future.

**Comment by dazuimao1990** [comment]
@wonderflow Translation work has been completed, review the PR #846  please.

**Comment by dazuimao1990** [comment]
This issue can be closed and maybe I can get a T-shirt. hahah 😜

**Comment by wonderflow** [comment]
@dazuimao1990 please contact me in DingTalk
