### ISSUE TITLE
translate of multi-cluster authorization mechanism

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela.io#811]
https://kubevela.io/zh/docs/next/platform-engineers/auth/advance

**Comment by oudi** [comment]
I would like to translate this doc. assign to me:)

**Comment by oudi** [comment]
@wonderflow The pull request https://github.com/kubevela/kubevela.io/pull/856 have passed basic checks. not quite sure some translation of the concepts corrected. need your suggestions.

**Comment by oudi** [comment]
@Somefive
 Apply suggestions from code review https://github.com/kubevela/kubevela.io/pull/856
