### ISSUE TITLE
translate of build addon registry

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela.io#814]
https://kubevela.io/zh/docs/next/platform-engineers/addon/addon-registry

**Comment by charlie0129** [comment]
It's better that this translation happen after #792 gets merged, to prevent unnecessary re-translations.

> It is now merged. Anyone who is interested in translating this is welcomed to grab it.

**Comment by charlie0129** [comment]
Just a quick note: please switch to the English doc for the latest version https://kubevela.net/docs/next/platform-engineers/addon/addon-registry
