### ISSUE TITLE
I still had to install a gzip tool (like cygwin) and added it the environment variables as explained here https://stackoverflow.com/questions/36733176/how-do-i-add-a-gzip-command-to-windows-cmd

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela.io#892]
I still had to install a gzip tool (like cygwin) and added it the environment variables as explained here https://stackoverflow.com/questions/36733176/how-do-i-add-a-gzip-command-to-windows-cmd
to get it up and running

_Originally posted by @BartNetJS in https://github.com/kubevela/kubevela.io/issues/710#issuecomment-1202719177_

**Comment by charlie0129** [comment]
It is here https://github.com/kubevela/kubevela/issues/4542

Let's close this.

**Comment by chivalryq** [comment]
Closing since it it fixed here: https://github.com/kubevela/velad/pull/74
