### ISSUE TITLE
translation of observability

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela.io#903]
https://kubevela.net/zh/docs/platform-engineers/operations/observability

**Comment by yangxggo** [comment]
I want to translate this one.

**Comment by yangxggo** [comment]
@wonderflow The pull request #952  has passed basic checks.

**Comment by yangxggo** [comment]
@wonderflow  The PR #952 has passed basic checks. Review required.

**Comment by yangxggo** [comment]
sorry, wrong click，please assign to me again.
