### ISSUE TITLE
"context: Workflow starting..."  the field is error,should is content

### ISSUE THREAD

**Issue by chenshiwei-io** [oam-dev/kubevela.io#956]
https://github.com/kubevela/kubevela.io/blob/47b98e0a569082767b83de5f16bbe074bd80280b/docs/end-user/workflow/built-in-workflow-defs.md?plain=1#L364

**Comment by FogDong** [comment]
Thanks for the report, it would be great if you can create a PR to fix it😊

**Comment by chenshiwei-io** [comment]
OK，I have now submitted
