### ISSUE TITLE
translate blog

### ISSUE THREAD

**Issue by yangxggo** [oam-dev/kubevela.io#963]
Does this blog need to translate? Assign to me if needed.
https://kubevela.net/zh/blog/2022/07/20/migrate-erraform-cloud-resources-to-kubeVela

**Comment by yangxggo** [comment]
By the way,  there is a spelling mistake —— terraform —— in the url of this blog.

**Comment by wonderflow** [comment]
Sure, please go ahead

**Comment by yangxggo** [comment]
@wonderflow The PR #973  has passed basic checks. Review required.

**Comment by yangxggo** [comment]
merged PR #973
